# dashboard.kv

#:import utils kivy.utils
<Dashboard>:
    canvas.before:
        Color:
            rgb: app.kynikuiController.theme.background
        Rectangle:
            size: self.size
            pos: self.pos

    BoxLayout:
        orientation: "vertical"
        size_hint: 1.0, 1.0

        BoxLayout:
            orientation: "horizontal"
            size_hint: 1.0, 1.0

            # Placeholder Image
            BoxLayout:
                orientation: "vertical"
                size_hint: .25, 0.8

            # Separator
            BoxLayout:
                orientation: "vertical"
                size_hint: .01, 0.8

                canvas.before:
                    Color:
                        rgb: app.kynikuiController.theme.buttons
                    Rectangle:
                        size: self.size
                        pos: self.pos

            # Buttons
            BoxLayout:
                orientation: "vertical"
                size_hint: .25, 0.8
                
                MDFlatButton:
                    icon: "folder-plus-outline"
                    text: "Open"
                    # md_bg_color: hex(app.kynikuiController.theme.buttons)
                    font_size: "20sp" # also sets icon size

                MDFillRoundFlatIconButton:
                    icon: "bookmark-multiple-outline"
                    text: "Continue"
                    # md_bg_color: hex(app.kynikuiController.theme.buttons)
                    font_size: "20sp" # also sets icon size

                MDFillRoundFlatIconButton:
                    icon: "book-open-page-variant-outline"
                    text: "Library"
                    # md_bg_color: hex(app.kynikuiController.theme.buttons)
                    font_size: "20sp" # also sets icon size

                MDFillRoundFlatIconButton:
                    icon: "cog-outline"
                    text: "Settings"
                    # md_bg_color: hex(app.kynikuiController.theme.buttons)
                    font_size: "20sp" # also sets icon size
